// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLxWnUncgdt40XivJIvYJfZ84ZLizODNY',
    appId: '1:530351230355:web:1d4c5ac7c9858c01882c66',
    messagingSenderId: '530351230355',
    projectId: 'fintrack-app-48c77',
    authDomain: 'fintrack-app-48c77.firebaseapp.com',
    storageBucket: 'fintrack-app-48c77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCazZu4P8bXF09ixpFasLTRQMu5nmGurvU',
    appId: '1:530351230355:android:85ba39292ce5519f882c66',
    messagingSenderId: '530351230355',
    projectId: 'fintrack-app-48c77',
    storageBucket: 'fintrack-app-48c77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaE_qrFhIpE2uapnpvUesWMyejtLN79xw',
    appId: '1:530351230355:ios:2303c1d13b0a507e882c66',
    messagingSenderId: '530351230355',
    projectId: 'fintrack-app-48c77',
    storageBucket: 'fintrack-app-48c77.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaE_qrFhIpE2uapnpvUesWMyejtLN79xw',
    appId: '1:530351230355:ios:2303c1d13b0a507e882c66',
    messagingSenderId: '530351230355',
    projectId: 'fintrack-app-48c77',
    storageBucket: 'fintrack-app-48c77.firebasestorage.app',
    iosBundleId: 'com.example.fintrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLxWnUncgdt40XivJIvYJfZ84ZLizODNY',
    appId: '1:530351230355:web:4a1bced8b76493c0882c66',
    messagingSenderId: '530351230355',
    projectId: 'fintrack-app-48c77',
    authDomain: 'fintrack-app-48c77.firebaseapp.com',
    storageBucket: 'fintrack-app-48c77.firebasestorage.app',
  );
}
